### ISSUE TITLE
Mouse and keyboard simulation doesn't work in lock screen

### ISSUE THREAD

**Issue by cherpake** [MediatedCommunications/WindowsInput#23]
Tried running the app as administrator, and even use requestedExecutionLevel as highestAvailable with uiAccess set to true, but input simulation won't work in Lock Screen. Either I'm missing something or the library can't simulate input when computer is locked?

**Comment by TonyValenti** [comment]
Hi @cherpake - I haven't investigated this, but I am about 99.9% certain this is because the Lock Screen is actually running in a different user context than your app. Windows intentionally isolates things like that because it would be a security risk to be able to simulate or listen to keys pressed in the login screen.
